MusicTransferWebApp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from . import views
# import views from local directory
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('ytAPI.urls', 'ytAPI'), namespace='ytAPI')),
    #path('', views.index, name="index"),
    path('about', views.about, name="about"),
    re_path(r'^celery-progress/', include('celery_progress.urls')),
] 

ytAPI/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

#from .views import IndexPageView, ChooseSourceView, ytsource, ytsourcecallback
from .views import *
urlpatterns = [
    path('', IndexPageView.as_view(), name='index'),
    path('ChooseSource/', ChoosePlatView.as_view(), name='chooseSource'),
    path('ChooseDest/', ChoosePlatView.as_view(), name='chooseDest'),
    path('ytAuth/', ytAuth, name='YTAuth'),
    path('ytsourcecallback/', ytsourcecallback, name='YToauth2callback'),
    path('ytGetData/', ytGetData, name='ytGetData'),
    path('spdestcallback/', spdestcallback, name='SPoauth2callback'),
    path('spAuth/', spAuth, name='SPAuth'),
    path('ytChoosePlaylist/', ytChoosePlaylist, name='ytChoosePlaylist'),
    path('ytGetSongs/', ytGetSongs, name='ytGetSongs'),
    path('customisePlaylist/', customisePlaylist, name='custPlaylist'),
    path('spCreatePlaylist/', spCreatePlaylist, name='spCreatePlaylist'),
    path('spTransfer/', spTransfer, name='spTransfer'),
    path('spTransferFinish/', spTransferFinish, name='spTransferFinish'),
    path('spLoop/', spWebLoop, name='spWebLoop'),
    path('Finish', Finish, name='Finish'),
    path('changePlatforms', ChangePlatforms, name='changePlatforms')
]

MusicTransferWebApp/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render

#def index(request):
 #   return render(request, 'index.html')
    #template = loader.get_template('index.html')
    #return HttpResponse(template.render({}, request))

def about(request):
    return render(request, 'about.html')

MusicTransferWebApp/templates/APIs/choosePlat.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Choose Platform{% endblock %}

{% block header %}
{% url 'ytAPI:chooseSource' as source_url %}
{% url 'ytAPI:chooseDest' as dest_url %}
Choose your platform!
{% if request.path == source_url %}
<button style="border-radius: 50%; align-content: center;" type="button" class="btn btn-light" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-bs-content="Choose the platform which you would like to transfer playlists from">
    <img src="{% static 'bootstrap/question-circle.svg' %}">
</button>
{% elif request.path == dest_url %}
<button style="border-radius: 50%; align-content: center;" type="button" class="btn btn-light" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-bs-content="Choose the platform where you would like to move your playlist to">
    <img src="{% static 'bootstrap/question-circle.svg' %}">
</button>
{% endif %}
{% endblock %}

{% block content %}
{% url 'ytAPI:YTAuth' as ytAuth %}
{% url 'ytAPI:chooseSource' as source_url %}
{% url 'ytAPI:SPAuth' as spAuth %}
{% url 'ytAPI:chooseDest' as dest_url %}
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<link rel="stylesheet" href="{% static 'APIs/buttons.css' %}">
<div id="source_options">
    <span></span>
    
    {% if request.path == source_url %}
    <a id="YTsource" class="logo_btn" href="{{ ytAuth }}"><img id="YTimg" class="circle" src="{% static 'APIs/youtube.png' %}"></a>
    {% else %}
    <img id="YTimg" class="circle" src="{% static 'APIs/youtube.png' %}">
    {% endif %}
    
    {% if request.path == dest_url %}
    <a id="SFsource" class="logo_btn" href="{{ spAuth }}"><img id="SFimg" class="circle" src="{% static 'APIs/spotify.png' %}"></a>
    {% else %}
    <img id="YTimg" class="circle" src="{% static 'APIs/spotify.png' %}">
    {% endif %}
    <span></span>
</div>

{% endblock %}

MusicTransferWebApp/templates/APIs/chooseplaylist.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Choose Playlist{% endblock %}
{% block header %}
Choose your playlist!
<button style="border-radius: 50%; align-content: center;" type="button" class="btn btn-light" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-bs-content="Select a playlist that you would like to transfer and click 'Submit'!">
    <img src="{% static 'bootstrap/question-circle.svg' %}">
</button>
{% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<script src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>

<h1><b>Choose a playlist!</b></h1>
{% url 'ytAPI:ytGetSongs' as songs_url %}
<form action="{{ songs_url }}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <select class="form-control" id="inputGroupSelect04" aria-label="Select playlist" name="playlist">
            {% for item in playlist_list %}
            {% if forloop.counter0 == 0 %}
            <option value="{{ forloop.counter0 }}" selected>{{ item.name }}</option>
            {% else %}
            <option value="{{ forloop.counter0 }}">{{ item.name }}</option>
            {% endif %}
            {% endfor %}
        </select>
        <button class="btn btn-outline-secondary" type="submit">Submit</button>
    </div>
</form>
<hr>
<h2>Or enter a link to a playlist!</h2>
<form action="{{ songs_url }}" method="POST">
    {% csrf_token %}
<label for="basic-url" class="form-label">Enter the playlist ID in the space</label>
<div class="input-group mb-3">
  <span class="input-group-text" id="basic-addon3">https://www.youtube.com/playlist?list=</span>
  <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3" name="play_id">
</div>
<button class="btn btn-outline-secondary" type="submit">Submit</button>
</form>
{% endblock %}

MusicTransferWebApp/templates/APIs/customiseplaylist.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Customise Playlist{% endblock %}

{% block header %}
Customise your new playlist!
<button style="border-radius: 50%; align-content: center;" type="button" class="btn btn-light" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-bs-content="Customise the name, description and public settings of your destination playlist here!">
    <img src="{% static 'bootstrap/question-circle.svg' %}">
</button>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

{% url 'ytAPI:spCreatePlaylist' as sp_url %}
<form action="{{ sp_url }}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label for="playTitle" class="form-label">Playlist name (Required)</label>
        <input maxlength="100" name="play_name" type="text"  class="form-control" id="playTitle" value="{{ fill_name }}" required>
        <div class="invalid-feedback">
            Please enter a title for your playlist
        </div>
    </div>
    <div class="mb-3">
        <label for="playDesc" class="form-label">Playlist description (Optional)</label>
        <textarea maxlength="300" name="play_description" class="form-control" id="playDesc" rows="3"></textarea>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="checkbox" value="True" id="flexCheckChecked" name="play_setting">
        <label class="form-check-label" for="flexCheckChecked">
          Public playlist (Check this if you would like your new playlist to be public)
        </label>
    </div>
    <button class="btn btn-light btn-outline-secondary" type="submit">Submit</button>
</form>

{% endblock %}

MusicTransferWebApp/templates/APIs/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block header %}
MyMusync
{% endblock %}

{% block content %}

{% url 'ytAPI:chooseSource' as source_url %}

<!-- insert button css if necessary-->
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script> 
<link rel="stylesheet" href="{% static 'main/process.css' %}">

<div id="Processes">
    <div id="start" class="Process">
        <h1>Transfer your music!</h1>
        <h2>Click below to start your transfer</h2>
        <button class="btn btn-light" id="startButton" onclick="location.href = '{{ source_url }}'"><b>START</b></button>
    </div>
</div>

{% endblock %}

MusicTransferWebApp/templates/APIs/transferFinish.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Transfer Finish{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
Transfer finished!
<button style="border-radius: 50%; align-content: center;" type="button" class="btn btn-light" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-bs-content="Thank you for using this service, below you can see the items that we couldn't transfer or find on your destination platform">
    <img src="{% static 'bootstrap/question-circle.svg' %}">
</button>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Song/Video Name</th>
        </tr>
    </thead>
    <tbody>
    {% for item in unavailable_list %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ item.0 }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% url 'ytAPI:spWebLoop' as link_url %}
<a href="{{ link_url }}" class="btn btn-outline-light" role="button">Continue</a>
{% endblock %}

MusicTransferWebApp/templates/APIs/webLoop.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Next Steps{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
All done!
<button style="border-radius: 50%; align-content: center;" type="button" class="btn btn-light" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-bs-content="Please now choose whether you would like to finish your visit, transfer a different playlist between the same platforms or to change your platforms.">
    <img src="{% static 'bootstrap/question-circle.svg' %}">
</button>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<div class="col-auto d-flex flex-column">
{% url 'ytAPI:Finish' as finish_url %}
<a href="{{ finish_url }}" class="btn btn-outline-light" role="button">Finish</a>

{% url 'ytAPI:ytChoosePlaylist' as play_url %}
<a href="{{ play_url }}" class="btn btn-outline-light" role="button">Transfer another playlist</a>

{% url 'ytAPI:changePlatforms' as plat_url %}
<a href="{{ plat_url }}" class="btn btn-outline-light" role="button">Change platforms</a>

</div>
{% endblock %}