MusicTransferWebApp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from . import views
# import views from local directory
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('ytAPI.urls', 'ytAPI'), namespace='ytAPI')),
    #path('', views.index, name="index"),
    path('about', views.about, name="about"),
    re_path(r'^celery-progress/', include('celery_progress.urls')),
] 

ytAPI/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

#from .views import IndexPageView, ChooseSourceView, ytsource, ytsourcecallback
from .views import *
urlpatterns = [
    path('', IndexPageView.as_view(), name='index'),
    path('ChooseSource/', ChoosePlatView.as_view(), name='chooseSource'),
    path('ChooseDest/', ChoosePlatView.as_view(), name='chooseDest'),
    path('ytAuth/', ytAuth, name='YTAuth'),
    path('ytsourcecallback/', ytsourcecallback, name='YToauth2callback'),
    path('ytGetData/', ytGetData, name='ytGetData'),
    path('spdestcallback/', spdestcallback, name='SPoauth2callback'),
    path('spAuth/', spAuth, name='SPAuth'),
    path('ytChoosePlaylist/', ytChoosePlaylist, name='ytChoosePlaylist'),
    path('ytGetSongs/', ytGetSongs, name='ytGetSongs'),
    path('customisePlaylist/', customisePlaylist, name='custPlaylist'),
    path('spCreatePlaylist/', spCreatePlaylist, name='spCreatePlaylist'),
    path('spTransfer/', spTransfer, name='spTransfer'),
    path('spTransferFinish/', spTransferFinish, name='spTransferFinish'),
    path('spLoop/', spWebLoop, name='spWebLoop'),
    path('Finish', Finish, name='Finish'),
    path('changePlatforms', ChangePlatforms, name='changePlatforms')
]

MusicTransferWebApp/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render

#def index(request):
 #   return render(request, 'index.html')
    #template = loader.get_template('index.html')
    #return HttpResponse(template.render({}, request))

def about(request):
    return render(request, 'about.html')

MusicTransferWebApp/templates/about.html
{% extends "base.html" %}

{% block title %}About{% endblock %}

{% block header %}About the Site{% endblock %}
{% block nav %}
{% include 'navbar.html' %}
{% endblock %}
{% block content %}
New about page
{% endblock %}

MusicTransferWebApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script> 
    <link rel="stylesheet" type="text/css" href="{% static 'main/base.css' %}">
</head>

<body style="background-color: #212529; color: #fff;">

    <h1><b>{% block header %}{% endblock %}</b></h1>

    <hr>
    {% block nav %}{% endblock %}
    <hr>
    <div class="content-box">
    <main>
        {% block content %}
        {% endblock %}
    </main>
    </div>
    <script>
        const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
        const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))
     </script>
</body>
</html>

MusicTransferWebApp/templates/navbar.html
{% load static %}

<link rel="stylesheet" href="{% static 'nav/navbar.css' %}">
<div class="nav">

    {% url 'ytAPI:index' as index_url %}
    <span>{% if request.path == index_url %}Home{% else %}<a href="{{ index_url }}" >Home</a>{% endif %}</span> |

    {%url 'about' as about_url %}
    <span>{% if request.path == about_url %}About{% else %}<a href="{{ about_url }}" >About</a>{% endif %}</span> 
    
</div>